"""rename project id column again

Revision ID: 083fbcd4981c
Revises: 2f3ff3f82630
Create Date: 2017-07-25 16:51:24.554452

"""

# revision identifiers, used by Alembic.
revision = '083fbcd4981c'
down_revision = '2f3ff3f82630'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('proteomics_id', sa.String(), nullable=True))
    op.drop_constraint(u'project_project_id_key', 'project', type_='unique')
    op.create_unique_constraint(None, 'project', ['proteomics_id'])
    op.drop_column('project', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'project', type_='unique')
    op.create_unique_constraint(u'project_project_id_key', 'project', ['project_id'])
    op.drop_column('project', 'proteomics_id')
    # ### end Alembic commands ###
