"""add columns to project

Revision ID: 58d661e1c431
Revises: 
Create Date: 2017-07-11 14:55:50.319059

"""

# revision identifiers, used by Alembic.
revision = '58d661e1c431'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('completion_date', sa.Date(), nullable=True))
    op.add_column('project', sa.Column('description', sa.String(length=1024), nullable=True))
    op.add_column('project', sa.Column('experiment_type', sa.String(length=32), nullable=True))
    op.add_column('project', sa.Column('research_group', sa.String(length=64), nullable=True))
    op.add_column('project', sa.Column('source', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'source')
    op.drop_column('project', 'research_group')
    op.drop_column('project', 'experiment_type')
    op.drop_column('project', 'description')
    op.drop_column('project', 'completion_date')
    ### end Alembic commands ###
