"""change experimental_details type to text

Revision ID: 75fc0ef1f064
Revises: b8828a83bdcf
Create Date: 2017-07-26 16:55:15.624865

"""

# revision identifiers, used by Alembic.
revision = '75fc0ef1f064'
down_revision = 'b8828a83bdcf'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'experimental_details')
    op.add_column('project', sa.Column('experimental_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('experimental_details', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
