"""add ondelete

Revision ID: b8828a83bdcf
Revises: cd37329c3929
Create Date: 2017-07-26 16:17:36.386315

"""

# revision identifiers, used by Alembic.
revision = 'b8828a83bdcf'
down_revision = 'cd37329c3929'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'peptide_protein_id_fkey', 'peptide', type_='foreignkey')
    op.create_foreign_key(u'peptide_protein_id_fkey', 'peptide', 'protein', ['protein_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'protein_project_id_fkey', 'protein', type_='foreignkey')
    op.create_foreign_key(u'protein_project_id_fkey', 'protein', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'protein_project_id_fkey', 'protein', type_='foreignkey')
    op.create_foreign_key(u'protein_project_id_fkey', 'protein', 'project', ['project_id'], ['id'])
    op.drop_constraint(u'protein_project_id_fkey', 'peptide', type_='foreignkey')
    op.create_foreign_key(u'peptide_protein_id_fkey', 'peptide', 'protein', ['protein_id'], ['id'])
    # ### end Alembic commands ###
