"""remove project name column

Revision ID: cd37329c3929
Revises: 083fbcd4981c
Create Date: 2017-07-25 16:53:40.551856

"""

# revision identifiers, used by Alembic.
revision = 'cd37329c3929'
down_revision = '083fbcd4981c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'project_name_key', 'project', type_='unique')
    op.drop_column('project', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'project_name_key', 'project', ['name'])
    # ### end Alembic commands ###
